version: 2
jobs:
  build:
    docker:
      - image: vault:latest
    working_directory:  ~/tf_vault
    steps:
      - add_ssh_keys:
          fingerprints:
            "41:cc:09:01:8c:6b:56:ec:ac:da:e6:bb:98:0c:5d:e9"
      - run:
          name: install git
          command: |
            apk update
            apk add git
      - checkout:
          path: ~/src/github.com/nearmap/tf_vault
